# Generated by Django 3.2.9 on 2022-01-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='page_images',
            field=models.ManyToManyField(blank=True, related_name='pages_images', to='books.Image'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='canvas',
            field=models.TextField(null=True),
        ),
    ]
