# Generated by Django 3.1.11 on 2022-01-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20220126_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='', upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.pages'),
        ),
    ]
