# Generated by Django 3.1.11 on 2022-01-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20220126_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='cover',
            field=models.ImageField(default='', upload_to='books'),
            preserve_default=False,
        ),
    ]
