# Generated by Django 3.1.11 on 2022-01-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20220126_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='cover',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
